<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ODD" nsURI="http://www.example.org/ODD" nsPrefix="ODD">
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="#//EntityReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionCall" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" upperBound="-1"
        eType="#//Actual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="called" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actual" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyEntity" eSuperTypes="#//EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyEnvironment" eSuperTypes="#//EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="#//AreaEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AreaEnumeration">
    <eLiterals name="bottom"/>
    <eLiterals name="left"/>
    <eLiterals name="right"/>
    <eLiterals name="top"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignAttribute" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//AttributeAccess"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeAccess" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessWho" eType="#//SpecialEntities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//GeneralAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeInit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisation" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//UserDefinedAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSampling" eSuperTypes="#//Sampling">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//UserDefinedAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binary" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" upperBound="-1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
    <eLiterals name="add"/>
    <eLiterals name="subtract"/>
    <eLiterals name="multiply"/>
    <eLiterals name="divide"/>
    <eLiterals name="distance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConstant" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categorical" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeEnvironment" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" eType="#//EnvironmentEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Characterization" eSuperTypes="#//LetDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clone" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountOfClones" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloneValues" upperBound="-1"
        eType="#//SetAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Code" abstract="true" eSuperTypes="#//IDescribedConcept #//IRationaledConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myCode" lowerBound="1"
        eType="#//Code"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collect" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CollectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
    <eLiterals name="Sum"/>
    <eLiterals name="Min"/>
    <eLiterals name="Max"/>
    <eLiterals name="Mean"/>
    <eLiterals name="Count"/>
    <eLiterals name="Percentage"/>
    <eLiterals name="StdDev"/>
    <eLiterals name="TODO_REMOVE_Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//CollectionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colour" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColourConstant" eSuperTypes="#//Colour">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colour" eType="#//ColourEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColourEnumeration">
    <eLiterals name="blue"/>
    <eLiterals name="silver"/>
    <eLiterals name="white"/>
    <eLiterals name="orange"/>
    <eLiterals name="black"/>
    <eLiterals name="grey"/>
    <eLiterals name="gold"/>
    <eLiterals name="pink"/>
    <eLiterals name="yellow"/>
    <eLiterals name="teal"/>
    <eLiterals name="aquamarine"/>
    <eLiterals name="brown"/>
    <eLiterals name="magenta"/>
    <eLiterals name="green"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparison" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="eq"/>
    <eLiterals name="ne"/>
    <eLiterals name="lt"/>
    <eLiterals name="le"/>
    <eLiterals name="gt"/>
    <eLiterals name="ge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalEntity" eType="#//GeneralEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalAction" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Comparison" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yesActivities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noActivities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionWith" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparison" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseEntityAttributes" eType="#//EntityBaseAttributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionWithSame" eSuperTypes="#//ConditionWith"/>
  <eClassifiers xsi:type="ecore:EClass" name="CountAllEntities" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" eType="#//Comparison"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="what" lowerBound="1" eType="#//SelectExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CountEntities" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where" eType="#//CountLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countCondition" eType="#//ConditionWith"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CountLocation">
    <eLiterals name="all"/>
    <eLiterals name="neighbour"/>
    <eLiterals name="same"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataCollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timesteps" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="REMOVE_collect" upperBound="-1"
        eType="#//AttributeAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="REMOVE_collectsyn" upperBound="-1"
        eType="#//LetCollect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionItem" upperBound="-1"
        eType="#//CollectionItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecrementAttribute" eSuperTypes="#//AssignAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Density" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="percentage" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionElement" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptionText" upperBound="-1"
        eType="#//InformalText" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignConcepts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensing" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emergence" eType="#//InformalWithRationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptation" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learning" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prediction" eType="#//InformalWithRationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectives" upperBound="-1"
        eType="#//InformalText" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="ahead"/>
    <eLiterals name="right"/>
    <eLiterals name="left"/>
    <eLiterals name="back"/>
    <eLiterals name="backwards"/>
    <eLiterals name="north"/>
    <eLiterals name="south"/>
    <eLiterals name="east"/>
    <eLiterals name="west"/>
    <eLiterals name="random"/>
    <eLiterals name="aheadRandom"/>
    <eLiterals name="rightRandom"/>
    <eLiterals name="leftRandom"/>
    <eLiterals name="backRandom"/>
    <eLiterals name="backwardsRandom"/>
    <eLiterals name="northRandom"/>
    <eLiterals name="southRandom"/>
    <eLiterals name="eastRandom"/>
    <eLiterals name="westRandom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementWise" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndCondition" abstract="true" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entities" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where" eType="#//CountLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countCondition" eType="#//ConditionWith"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionwith" eType="#//ConditionWith"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntitiesStateVariablesAndScales">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelParameters" upperBound="-1"
        eType="#//GeneralAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityAttributes" upperBound="-1"
        eType="#//GeneralAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentEntities" upperBound="-1"
        eType="#//EnvironmentEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentAttributes"
        upperBound="-1" eType="#//GeneralAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networks" upperBound="-1"
        eType="#//Network" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticAttributes" upperBound="-1"
        eType="#//LetActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntheticModelAttributes"
        upperBound="-1" eType="#//LetActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale" eType="#//Rationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scales" eType="#//InformalWithRationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesInit" upperBound="-1"
        eType="#//AttributeInit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesInit" upperBound="-1"
        eType="#//EntityReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesStochasticity"
        upperBound="-1" eType="#//AttributeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//GeneralEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userDefinedAttributes"
        upperBound="-1" eType="#//GeneralAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colour" eType="#//ColourConstant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" lowerBound="1" eType="#//Shape"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationNumberOfEntities"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationDistribution"
        eType="#//InitialEntityDistribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initAttributes" upperBound="-1"
        eType="#//AttributeInit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityAccess" eSuperTypes="#//SelectExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//EntityReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EntityBaseAttributes">
    <eLiterals name="colour"/>
    <eLiterals name="shape"/>
    <eLiterals name="size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityExpression" eSuperTypes="#//Actual">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" eType="#//SpecialEntities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntitySampling" eSuperTypes="#//Sampling">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEntity" eSuperTypes="#//GeneralEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="themiswhatdoesthegridrepresent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultColour" eType="#//Colour"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationLocation"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where" eType="#//Where"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="envEntity" eType="#//EnvironmentEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Everywhere" eSuperTypes="#//Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentDefinition" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitions" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationEnd" upperBound="-1"
        eType="#//EndCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experimentWorld" eType="#//GraphicsWindow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experimentValues" upperBound="-1"
        eType="#//Sampling" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Experiments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataPresentation" upperBound="-1"
        eType="#//PresentationItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataCollection" eType="#//DataCollection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultWorld" eType="#//GraphicsWindow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experiments" upperBound="-1"
        eType="#//ExperimentDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Actual"/>
  <eClassifiers xsi:type="ecore:EClass" name="False" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilterIndex" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterCondition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedValue" eSuperTypes="#//SamplingMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForEach" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" eType="#//SpecialEntities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locals" upperBound="-1"
        eType="#//LetActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" upperBound="-1"
        eType="#//Actual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralAttribute" abstract="true" eSuperTypes="#//IDescribedConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralEntity" abstract="true" eSuperTypes="#//IDescribedConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicsWindow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrapHorizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrapVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pixelSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="worldSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//ColourConstant"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDescribedConcept" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElse" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positive" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negative" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncrementAttribute" eSuperTypes="#//AssignAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Indices" eSuperTypes="#//SelectExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformalText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformalWithRationale">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale" eType="#//Rationale"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialEntityDistribution" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partner2" lowerBound="1"
        eType="#//EntityReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRationaledConcept" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale" upperBound="-1"
        eType="#//Rationale" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KillEntity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="killWho" eType="#//SpecialEntities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetAccess" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="let" lowerBound="1" eType="#//LetActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetActivity" eSuperTypes="#//Activity #//IDescribedConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetCollect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//LetActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetDefinition" eSuperTypes="#//GeneralAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelCategories">
    <eLiterals name="Prediction"/>
    <eLiterals name="Explanation"/>
    <eLiterals name="Description"/>
    <eLiterals name="Theoretical_Exposition"/>
    <eLiterals name="Illustration"/>
    <eLiterals name="Analogy"/>
    <eLiterals name=" Social_Learning"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//ModelCategories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchQuestion" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetGroup" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purposeDescription" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalDescriptions" upperBound="-1"
        eType="#//DescriptionElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Move" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//GeneralEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directed" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userDefinedAttributes"
        upperBound="-1" eType="#//GeneralAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" eType="#//Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="number"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberConstant" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Numerical" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupiedSpot" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODD" eSuperTypes="#//IDescribedConcept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelDescription" lowerBound="1"
        eType="#//ModelDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesAndVariables" lowerBound="1"
        eType="#//EntitiesStateVariablesAndScales" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processAndScheduling" lowerBound="1"
        eType="#//ProcessOverviewAndScheduling" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designConcepts" eType="#//DesignConcepts"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodels" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experiments" lowerBound="1"
        eType="#//Experiments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale4Init" eType="#//Rationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationales" upperBound="-1"
        eType="#//RationaleReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//EntityReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthesis" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Percentage" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//CollectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaling" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessOverviewAndScheduling">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endconditions" upperBound="-1"
        eType="#//EndCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codes" upperBound="-1"
        eType="#//Code" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" upperBound="-1"
        eType="#//ActionCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale4Schedule" eType="#//Rationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stochasticityCode" upperBound="-1"
        eType="#//CodeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedCondition" eSuperTypes="#//EndCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" eType="#//Quantifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//GeneralEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedConditionWithComparison" eSuperTypes="#//QuantifiedCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comp" eType="#//Comparison" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//GeneralAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="ALL"/>
    <eLiterals name="NOTALL"/>
    <eLiterals name="ANY"/>
    <eLiterals name="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="#//InitialEntityDistribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomNormal" eSuperTypes="#//RandomNumber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stdev" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomNumber" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomUniform" eSuperTypes="#//RandomNumber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeSampling" eSuperTypes="#//SamplingMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="increment" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeType" eSuperTypes="#//Numerical">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rationale">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base4Rationale" eType="#//RationaleKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentence" upperBound="-1"
        eType="#//InformalText" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RationaleKind">
    <eLiterals name="Adhoc"/>
    <eLiterals name="EstablisedTheory"/>
    <eLiterals name="Observation"/>
    <eLiterals name="Combination"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RationaleReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ratConcept" lowerBound="1"
        eType="#//IRationaledConcept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sampling" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//SamplingMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SamplingMethod" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScaledColour" eSuperTypes="#//ColourConstant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scalingValue" lowerBound="1"
        eType="#//AttributeAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectN" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where" eType="#//Where"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="count" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
        eType="#//SelectExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetAttribute" eSuperTypes="#//AssignAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shape">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//ShapeEnumeration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ShapeEnumeration">
    <eLiterals name="default"/>
    <eLiterals name="airplane"/>
    <eLiterals name="arrow"/>
    <eLiterals name="box"/>
    <eLiterals name="bug"/>
    <eLiterals name="butterfly"/>
    <eLiterals name="car"/>
    <eLiterals name="circle"/>
    <eLiterals name="circle_2"/>
    <eLiterals name="cow"/>
    <eLiterals name="cylinder"/>
    <eLiterals name="dot"/>
    <eLiterals name="face_happy"/>
    <eLiterals name="face_neutral"/>
    <eLiterals name="face_sad"/>
    <eLiterals name="fish"/>
    <eLiterals name="flag"/>
    <eLiterals name="flower"/>
    <eLiterals name="house"/>
    <eLiterals name="leaf"/>
    <eLiterals name="line"/>
    <eLiterals name="line_half"/>
    <eLiterals name="pentagon"/>
    <eLiterals name="person"/>
    <eLiterals name="plant"/>
    <eLiterals name="sheep"/>
    <eLiterals name="square"/>
    <eLiterals name="square_2"/>
    <eLiterals name="star"/>
    <eLiterals name="target"/>
    <eLiterals name="tree"/>
    <eLiterals name="triangle"/>
    <eLiterals name="triangle_2"/>
    <eLiterals name="truck"/>
    <eLiterals name="turtle"/>
    <eLiterals name="wheel"/>
    <eLiterals name="x"/>
    <eLiterals name="wolf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slider" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slideAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startValue" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SpecialEntities">
    <eLiterals name="me"/>
    <eLiterals name="other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedCondition" eSuperTypes="#//EndCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="True" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedAttribute" eSuperTypes="#//GeneralAttribute #//IRationaledConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Where">
    <eLiterals name="sameSpot"/>
    <eLiterals name="neighbour"/>
    <eLiterals name="anywhere"/>
  </eClassifiers>
</ecore:EPackage>
