package formalodd.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Objects;

public class GraphicsWindow_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("to setup");
    tgs.newLine();
    tgs.append("clear-all");
    tgs.newLine();
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de04bL, "BackGround")) != null) {
      tgs.append("ask patches[ set pcolor ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de04bL, "BackGround")));
      tgs.append(" ");
      tgs.append("]");
      tgs.newLine();

    }
    tgs.append("ask patches [");
    tgs.newLine();
    tgs.append("]");
    tgs.newLine();

    tgs.append("reset-ticks");
    tgs.newLine();
    tgs.append("end");
    tgs.newLine();
    tgs.append("to go");
    tgs.newLine();
    tgs.append("ask patches[");
    tgs.newLine();
    tgs.append("]");
    tgs.newLine();
    tgs.append("tick");
    tgs.newLine();
    tgs.append("end");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("GRAPHICS-WINDOW");
    tgs.newLine();
    tgs.append("210");
    tgs.newLine();
    tgs.append("10");
    tgs.newLine();
    tgs.append("647");
    tgs.newLine();
    tgs.append("448");
    tgs.newLine();
    tgs.append("-1");
    tgs.newLine();
    tgs.append("-1");
    tgs.newLine();
    if (!(Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de04eL, "PixelSize")), null))) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de04eL, "PixelSize")));
      tgs.newLine();
    }
    if (Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de04eL, "PixelSize")), null)) {
      tgs.append("2");
    }

    tgs.append("1");
    tgs.newLine();
    tgs.append("10");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("0");
    tgs.newLine();
    if (!(Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de052L, "WrapHorizontal")), null)) && !(Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662ded2cL, "WrapVertical")), null))) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de052L, "WrapHorizontal")));
      tgs.newLine();
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662ded2cL, "WrapVertical")));
      tgs.newLine();
    }
    if (Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662de052L, "WrapHorizontal")), null) || Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662ded2cL, "WrapVertical")), null)) {
      tgs.append("0");
      tgs.newLine();
      tgs.append("0");
      tgs.newLine();
    }
    tgs.append("1");
    tgs.newLine();
    if (!(Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")), null))) {
      tgs.append("-");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")));
      tgs.newLine();
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")));
      tgs.newLine();
      tgs.append("-");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")));
      tgs.newLine();
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")));
      tgs.newLine();
    }
    if (Objects.equals(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L, 0x35a03919662f32cfL, "WorldSize")), null)) {
      tgs.append("-16");
      tgs.newLine();
      tgs.append("16");
      tgs.newLine();
      tgs.append("-16");
      tgs.newLine();
      tgs.append("16");
      tgs.newLine();
    }
    tgs.append("1");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("ticks");
    tgs.newLine();
    tgs.append("30.0");
    tgs.newLine();
    tgs.newLine();
    tgs.append("BUTTON");
    tgs.newLine();
    tgs.append("9");
    tgs.newLine();
    tgs.append("12");
    tgs.newLine();
    tgs.append("72");
    tgs.newLine();
    tgs.append("45");
    tgs.newLine();
    tgs.append("setup");
    tgs.newLine();
    tgs.append("setup");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("T");
    tgs.newLine();
    tgs.append("OBSERVER");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.newLine();
    tgs.append("BUTTON");
    tgs.newLine();
    tgs.append("89");
    tgs.newLine();
    tgs.append("11");
    tgs.newLine();
    tgs.append("152");
    tgs.newLine();
    tgs.append("44");
    tgs.newLine();
    tgs.append("go");
    tgs.newLine();
    tgs.append("go");
    tgs.newLine();
    tgs.append("T");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.append("T");
    tgs.newLine();
    tgs.append("OBSERVER");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("NIL");
    tgs.newLine();
    tgs.append("1");
    tgs.newLine();
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("NetLogo 6.0.4");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();
    tgs.append("@#$#@#$#@");
    tgs.newLine();


  }
}
