package formalodd.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int AgentStatistic = 1;
  public static final int AgentStatisticOptions = 2;
  public static final int Area = 3;
  public static final int Attribute = 4;
  public static final int AttributeStabelOption = 5;
  public static final int AttributeValueOptions = 6;
  public static final int Average = 7;
  public static final int Boolean = 8;
  public static final int Color = 9;
  public static final int ColorOptions = 10;
  public static final int ColorShade = 11;
  public static final int Conditional = 12;
  public static final int ConditionalAttribute = 13;
  public static final int ConditionalColor = 14;
  public static final int Coordinates = 15;
  public static final int Count = 16;
  public static final int DefaultColor = 17;
  public static final int DefaultShape = 18;
  public static final int Density = 19;
  public static final int EntitiesStateScales = 20;
  public static final int Entity = 21;
  public static final int EntityReference = 22;
  public static final int Environment = 23;
  public static final int EnvironmentEntity = 24;
  public static final int Exponential = 25;
  public static final int Expression = 26;
  public static final int Float = 27;
  public static final int Gamma = 28;
  public static final int GraphicsWindow = 29;
  public static final int Integer = 30;
  public static final int IntentionEffect = 31;
  public static final int Intentions = 32;
  public static final int Location = 33;
  public static final int Max = 34;
  public static final int Min = 35;
  public static final int MoreColors = 36;
  public static final int MoreShapes = 37;
  public static final int Names = 38;
  public static final int Normal = 39;
  public static final int ODD = 40;
  public static final int Poisson = 41;
  public static final int Shape = 42;
  public static final int ShapeInstance = 43;
  public static final int ShapeOptions = 44;
  public static final int Slider = 45;
  public static final int SliderOption = 46;
  public static final int SpecificLocation = 47;
  public static final int SpecificXY = 48;
  public static final int StatisticalDistribution = 49;
  public static final int String = 50;
  public static final int Stringvalue = 51;
  public static final int Sum = 52;
  public static final int Type = 53;
  public static final int UserComment = 54;
  public static final int UserDefinedAttribute = 55;
  public static final int test = 56;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L);
    builder.put(0x35a039196620dc12L, Action);
    builder.put(0x354cc3720a9ec553L, AgentStatistic);
    builder.put(0x2ae68cf577e9b56L, AgentStatisticOptions);
    builder.put(0x354cc3720a9ec5c8L, Area);
    builder.put(0x2ae68cf5798985aL, Attribute);
    builder.put(0x2ae68cf5790c5b0L, AttributeStabelOption);
    builder.put(0x2ae68cf57a8c7ebL, AttributeValueOptions);
    builder.put(0x354cc3720a9ec55aL, Average);
    builder.put(0x354cc3720a9ec52dL, Boolean);
    builder.put(0x354cc3720a9ec574L, Color);
    builder.put(0x35a039196585f0bdL, ColorOptions);
    builder.put(0x354cc3720a9ec592L, ColorShade);
    builder.put(0x354cc3720a9ec5c0L, Conditional);
    builder.put(0x354cc3720a9ec5b7L, ConditionalAttribute);
    builder.put(0x354cc3720a9ec58dL, ConditionalColor);
    builder.put(0x354cc3720a9ec5d0L, Coordinates);
    builder.put(0x354cc3720a9ec55dL, Count);
    builder.put(0x354cc3720a9ec585L, DefaultColor);
    builder.put(0x354cc3720a9ec575L, DefaultShape);
    builder.put(0x354cc3720a9ec5d6L, Density);
    builder.put(0x354cc3720a9ec508L, EntitiesStateScales);
    builder.put(0x354cc3720a9ec50eL, Entity);
    builder.put(0x2045364d4552674aL, EntityReference);
    builder.put(0x354cc3720a9ec597L, Environment);
    builder.put(0x354cc3720a9ec5a4L, EnvironmentEntity);
    builder.put(0x354cc3720a9ec550L, Exponential);
    builder.put(0x354cc3720a9ec5c3L, Expression);
    builder.put(0x354cc3720a9ec536L, Float);
    builder.put(0x354cc3720a9ec541L, Gamma);
    builder.put(0x35a0391965add532L, GraphicsWindow);
    builder.put(0x354cc3720a9ec52eL, Integer);
    builder.put(0x2045364d4534e56bL, IntentionEffect);
    builder.put(0x2045364d452f6abbL, Intentions);
    builder.put(0x354cc3720a9ec5c7L, Location);
    builder.put(0x354cc3720a9ec554L, Max);
    builder.put(0x354cc3720a9ec557L, Min);
    builder.put(0x354cc3720a9ec58aL, MoreColors);
    builder.put(0x354cc3720a9ec57bL, MoreShapes);
    builder.put(0x5be13da8667bda0cL, Names);
    builder.put(0x354cc3720a9ec547L, Normal);
    builder.put(0x354cc3720a9ec507L, ODD);
    builder.put(0x354cc3720a9ec54dL, Poisson);
    builder.put(0x354cc3720a9ec573L, Shape);
    builder.put(0x354cc3720a9ec57eL, ShapeInstance);
    builder.put(0x35a0391965961db8L, ShapeOptions);
    builder.put(0x36f982e7b7b77956L, Slider);
    builder.put(0x36f982e7b7b77a1eL, SliderOption);
    builder.put(0x354cc3720a9ec5c6L, SpecificLocation);
    builder.put(0x354cc3720a9ec5cbL, SpecificXY);
    builder.put(0x354cc3720a9ec53eL, StatisticalDistribution);
    builder.put(0x354cc3720a9ec523L, String);
    builder.put(0x354cc3720a9ec528L, Stringvalue);
    builder.put(0x354cc3720a9ec560L, Sum);
    builder.put(0x354cc3720a9ec522L, Type);
    builder.put(0x5be13da866785777L, UserComment);
    builder.put(0x354cc3720a9ec51fL, UserDefinedAttribute);
    builder.put(0x35a0391965de199dL, test);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
