package formalodd.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptAgentStatistic = createDescriptorForAgentStatistic();
  /*package*/ final ConceptDescriptor myConceptArea = createDescriptorForArea();
  /*package*/ final ConceptDescriptor myConceptAverage = createDescriptorForAverage();
  /*package*/ final ConceptDescriptor myConceptBoolean = createDescriptorForBoolean();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorOptions = createDescriptorForColorOptions();
  /*package*/ final ConceptDescriptor myConceptColorShade = createDescriptorForColorShade();
  /*package*/ final ConceptDescriptor myConceptConditional = createDescriptorForConditional();
  /*package*/ final ConceptDescriptor myConceptConditionalAttribute = createDescriptorForConditionalAttribute();
  /*package*/ final ConceptDescriptor myConceptConditionalColor = createDescriptorForConditionalColor();
  /*package*/ final ConceptDescriptor myConceptCoordinates = createDescriptorForCoordinates();
  /*package*/ final ConceptDescriptor myConceptCount = createDescriptorForCount();
  /*package*/ final ConceptDescriptor myConceptDefaultColor = createDescriptorForDefaultColor();
  /*package*/ final ConceptDescriptor myConceptDefaultShape = createDescriptorForDefaultShape();
  /*package*/ final ConceptDescriptor myConceptDensity = createDescriptorForDensity();
  /*package*/ final ConceptDescriptor myConceptEntitiesStateScales = createDescriptorForEntitiesStateScales();
  /*package*/ final ConceptDescriptor myConceptEntity = createDescriptorForEntity();
  /*package*/ final ConceptDescriptor myConceptEntityReference = createDescriptorForEntityReference();
  /*package*/ final ConceptDescriptor myConceptEnvironment = createDescriptorForEnvironment();
  /*package*/ final ConceptDescriptor myConceptEnvironmentEntity = createDescriptorForEnvironmentEntity();
  /*package*/ final ConceptDescriptor myConceptExponential = createDescriptorForExponential();
  /*package*/ final ConceptDescriptor myConceptExpression = createDescriptorForExpression();
  /*package*/ final ConceptDescriptor myConceptFloat = createDescriptorForFloat();
  /*package*/ final ConceptDescriptor myConceptGamma = createDescriptorForGamma();
  /*package*/ final ConceptDescriptor myConceptGraphicsWindow = createDescriptorForGraphicsWindow();
  /*package*/ final ConceptDescriptor myConceptInteger = createDescriptorForInteger();
  /*package*/ final ConceptDescriptor myConceptIntentionEffect = createDescriptorForIntentionEffect();
  /*package*/ final ConceptDescriptor myConceptIntentions = createDescriptorForIntentions();
  /*package*/ final ConceptDescriptor myConceptLocation = createDescriptorForLocation();
  /*package*/ final ConceptDescriptor myConceptMax = createDescriptorForMax();
  /*package*/ final ConceptDescriptor myConceptMin = createDescriptorForMin();
  /*package*/ final ConceptDescriptor myConceptMoreColors = createDescriptorForMoreColors();
  /*package*/ final ConceptDescriptor myConceptMoreShapes = createDescriptorForMoreShapes();
  /*package*/ final ConceptDescriptor myConceptNames = createDescriptorForNames();
  /*package*/ final ConceptDescriptor myConceptNormal = createDescriptorForNormal();
  /*package*/ final ConceptDescriptor myConceptODD = createDescriptorForODD();
  /*package*/ final ConceptDescriptor myConceptPoisson = createDescriptorForPoisson();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptShapeInstance = createDescriptorForShapeInstance();
  /*package*/ final ConceptDescriptor myConceptShapeOptions = createDescriptorForShapeOptions();
  /*package*/ final ConceptDescriptor myConceptSlider = createDescriptorForSlider();
  /*package*/ final ConceptDescriptor myConceptSliderOption = createDescriptorForSliderOption();
  /*package*/ final ConceptDescriptor myConceptSpecificLocation = createDescriptorForSpecificLocation();
  /*package*/ final ConceptDescriptor myConceptSpecificXY = createDescriptorForSpecificXY();
  /*package*/ final ConceptDescriptor myConceptStatisticalDistribution = createDescriptorForStatisticalDistribution();
  /*package*/ final ConceptDescriptor myConceptString = createDescriptorForString();
  /*package*/ final ConceptDescriptor myConceptStringvalue = createDescriptorForStringvalue();
  /*package*/ final ConceptDescriptor myConceptSum = createDescriptorForSum();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptUserComment = createDescriptorForUserComment();
  /*package*/ final ConceptDescriptor myConceptUserDefinedAttribute = createDescriptorForUserDefinedAttribute();
  /*package*/ final ConceptDescriptor myConcepttest = createDescriptorFortest();
  /*package*/ final EnumerationDescriptor myEnumerationColorenumeration = new EnumerationDescriptor_Colorenumeration();
  /*package*/ final EnumerationDescriptor myEnumerationShapeenumeration = new EnumerationDescriptor_Shapeenumeration();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptAgentStatistic, myConceptArea, myConceptAverage, myConceptBoolean, myConceptColor, myConceptColorOptions, myConceptColorShade, myConceptConditional, myConceptConditionalAttribute, myConceptConditionalColor, myConceptCoordinates, myConceptCount, myConceptDefaultColor, myConceptDefaultShape, myConceptDensity, myConceptEntitiesStateScales, myConceptEntity, myConceptEntityReference, myConceptEnvironment, myConceptEnvironmentEntity, myConceptExponential, myConceptExpression, myConceptFloat, myConceptGamma, myConceptGraphicsWindow, myConceptInteger, myConceptIntentionEffect, myConceptIntentions, myConceptLocation, myConceptMax, myConceptMin, myConceptMoreColors, myConceptMoreShapes, myConceptNames, myConceptNormal, myConceptODD, myConceptPoisson, myConceptShape, myConceptShapeInstance, myConceptShapeOptions, myConceptSlider, myConceptSliderOption, myConceptSpecificLocation, myConceptSpecificXY, myConceptStatisticalDistribution, myConceptString, myConceptStringvalue, myConceptSum, myConceptType, myConceptUserComment, myConceptUserDefinedAttribute, myConcepttest);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.AgentStatistic:
        return myConceptAgentStatistic;
      case LanguageConceptSwitch.Area:
        return myConceptArea;
      case LanguageConceptSwitch.Average:
        return myConceptAverage;
      case LanguageConceptSwitch.Boolean:
        return myConceptBoolean;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorOptions:
        return myConceptColorOptions;
      case LanguageConceptSwitch.ColorShade:
        return myConceptColorShade;
      case LanguageConceptSwitch.Conditional:
        return myConceptConditional;
      case LanguageConceptSwitch.ConditionalAttribute:
        return myConceptConditionalAttribute;
      case LanguageConceptSwitch.ConditionalColor:
        return myConceptConditionalColor;
      case LanguageConceptSwitch.Coordinates:
        return myConceptCoordinates;
      case LanguageConceptSwitch.Count:
        return myConceptCount;
      case LanguageConceptSwitch.DefaultColor:
        return myConceptDefaultColor;
      case LanguageConceptSwitch.DefaultShape:
        return myConceptDefaultShape;
      case LanguageConceptSwitch.Density:
        return myConceptDensity;
      case LanguageConceptSwitch.EntitiesStateScales:
        return myConceptEntitiesStateScales;
      case LanguageConceptSwitch.Entity:
        return myConceptEntity;
      case LanguageConceptSwitch.EntityReference:
        return myConceptEntityReference;
      case LanguageConceptSwitch.Environment:
        return myConceptEnvironment;
      case LanguageConceptSwitch.EnvironmentEntity:
        return myConceptEnvironmentEntity;
      case LanguageConceptSwitch.Exponential:
        return myConceptExponential;
      case LanguageConceptSwitch.Expression:
        return myConceptExpression;
      case LanguageConceptSwitch.Float:
        return myConceptFloat;
      case LanguageConceptSwitch.Gamma:
        return myConceptGamma;
      case LanguageConceptSwitch.GraphicsWindow:
        return myConceptGraphicsWindow;
      case LanguageConceptSwitch.Integer:
        return myConceptInteger;
      case LanguageConceptSwitch.IntentionEffect:
        return myConceptIntentionEffect;
      case LanguageConceptSwitch.Intentions:
        return myConceptIntentions;
      case LanguageConceptSwitch.Location:
        return myConceptLocation;
      case LanguageConceptSwitch.Max:
        return myConceptMax;
      case LanguageConceptSwitch.Min:
        return myConceptMin;
      case LanguageConceptSwitch.MoreColors:
        return myConceptMoreColors;
      case LanguageConceptSwitch.MoreShapes:
        return myConceptMoreShapes;
      case LanguageConceptSwitch.Names:
        return myConceptNames;
      case LanguageConceptSwitch.Normal:
        return myConceptNormal;
      case LanguageConceptSwitch.ODD:
        return myConceptODD;
      case LanguageConceptSwitch.Poisson:
        return myConceptPoisson;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.ShapeInstance:
        return myConceptShapeInstance;
      case LanguageConceptSwitch.ShapeOptions:
        return myConceptShapeOptions;
      case LanguageConceptSwitch.Slider:
        return myConceptSlider;
      case LanguageConceptSwitch.SliderOption:
        return myConceptSliderOption;
      case LanguageConceptSwitch.SpecificLocation:
        return myConceptSpecificLocation;
      case LanguageConceptSwitch.SpecificXY:
        return myConceptSpecificXY;
      case LanguageConceptSwitch.StatisticalDistribution:
        return myConceptStatisticalDistribution;
      case LanguageConceptSwitch.String:
        return myConceptString;
      case LanguageConceptSwitch.Stringvalue:
        return myConceptStringvalue;
      case LanguageConceptSwitch.Sum:
        return myConceptSum;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.UserComment:
        return myConceptUserComment;
      case LanguageConceptSwitch.UserDefinedAttribute:
        return myConceptUserDefinedAttribute;
      case LanguageConceptSwitch.test:
        return myConcepttest;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationColorenumeration, myEnumerationShapeenumeration);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Action", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a039196620dc12L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3864151261534280722");
    b.version(2);
    b.property("Who", 0x63dc23944092b2fcL).type(PrimitiveTypeId.STRING).origin("7195665424276697852").done();
    b.property("Conflict", 0x63dc23944092b2feL).type(PrimitiveTypeId.STRING).origin("7195665424276697854").done();
    b.property("Move", 0x63dc239440a5b6a3L).type(PrimitiveTypeId.STRING).origin("7195665424277943971").done();
    b.property("TurnRate", 0x770189b79ec364f9L).type(PrimitiveTypeId.STRING).origin("8575286587225761017").done();
    b.property("ChangePatches", 0x63dc23944530255bL).type(PrimitiveTypeId.STRING).origin("7195665424354125147").done();
    b.property("ChangeTurtle", 0x770189b79ec6646dL).type(PrimitiveTypeId.STRING).origin("8575286587225957485").done();
    b.property("TickTurtle", 0x770189b79ec6647cL).type(PrimitiveTypeId.STRING).origin("8575286587225957500").done();
    b.property("EndTurtle", 0x770189b79ec66474L).type(PrimitiveTypeId.STRING).origin("8575286587225957492").done();
    b.property("subAction", 0x13b41a7fe409020bL).type(PrimitiveTypeId.STRING).origin("1419788919117513227").done();
    b.aggregate("intention", 0x2045364d452f6abfL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d452f6abbL).optional(true).ordered(true).multiple(true).origin("2325324488107846335").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAgentStatistic() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055891");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForArea() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Area", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c8L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Location", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c7L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056008");
    b.version(2);
    b.property("selectlocations", 0x354cc3720a9ec5c9L).type(MetaIdFactory.dataTypeId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0xad0053c7aee25ecL)).origin("3840659476812056009").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAverage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Average", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec55aL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055898");
    b.version(2);
    b.associate("attribute", 0x354cc3720a9ec55bL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(false).origin("3840659476812055899").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Boolean", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec52dL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Type", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055853");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Color", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec574L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055924");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorOptions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ColorOptions", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a039196585f0bdL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3864151261524127933");
    b.version(2);
    b.property("Options", 0x35a039196585f0beL).type(PrimitiveTypeId.STRING).origin("3864151261524127934").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorShade() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ColorShade", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec592L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Color", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec574L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055954");
    b.version(2);
    b.property("ColorID", 0x354cc3720a9ec593L).type(MetaIdFactory.dataTypeId(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec588L)).origin("3840659476812055955").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConditional() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Conditional", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c0L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056000");
    b.version(2);
    b.property("EntitysEffected", 0x2045364d45311090L).type(PrimitiveTypeId.STRING).origin("2325324488107954320").done();
    b.property("PatchesEffected", 0x2045364d45311098L).type(PrimitiveTypeId.STRING).origin("2325324488107954328").done();
    b.property("attribute", 0x2045364d4531109fL).type(PrimitiveTypeId.STRING).origin("2325324488107954335").done();
    b.property("Condition", 0x2045364d45311093L).type(PrimitiveTypeId.STRING).origin("2325324488107954323").done();
    b.aggregate("intention", 0x2045364d4532b1d0L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d452f6abbL).optional(true).ordered(true).multiple(true).origin("2325324488108061136").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConditionalAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ConditionalAttribute", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5b7L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.EnvironmentEntity", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5a4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055991");
    b.version(2);
    b.property("attribute", 0x354cc3720a9ec5b8L).type(PrimitiveTypeId.STRING).origin("3840659476812055992").done();
    b.associate("attribute", 0x4b1fb43d68d055f5L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(true).origin("5413243452967114229").done();
    b.aggregate("conditional", 0x4b1fb43d68d055f3L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c0L).optional(true).ordered(true).multiple(false).origin("5413243452967114227").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConditionalColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ConditionalColor", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58dL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055949");
    b.version(2);
    b.property("Color", 0x354cc3720a9ec58eL).type(MetaIdFactory.dataTypeId(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec588L)).origin("3840659476812055950").done();
    b.aggregate("Conditional", 0x354cc3720a9ec590L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c0L).optional(true).ordered(true).multiple(false).origin("3840659476812055952").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCoordinates() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Coordinates", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d0L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056016");
    b.version(2);
    b.property("x", 0x354cc3720a9ec5d1L).type(PrimitiveTypeId.STRING).origin("3840659476812056017").done();
    b.property("y", 0x354cc3720a9ec5d3L).type(PrimitiveTypeId.STRING).origin("3840659476812056019").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCount() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Count", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec55dL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055901");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDefaultColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "DefaultColor", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec585L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Color", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec574L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055941");
    b.version(2);
    b.property("ColorID", 0x354cc3720a9ec586L).type(MetaIdFactory.dataTypeId(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec588L)).origin("3840659476812055942").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDefaultShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "DefaultShape", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec575L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Shape", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec573L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055925");
    b.version(2);
    b.property("Shapeid", 0x354cc3720a9ec577L).type(MetaIdFactory.dataTypeId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0xad0053c7aee25ecL)).origin("3840659476812055927").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDensity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Density", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d6L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.SpecificLocation", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c6L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056022");
    b.version(2);
    b.property("percentage", 0x354cc3720a9ec5d7L).type(PrimitiveTypeId.STRING).origin("3840659476812056023").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntitiesStateScales() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "EntitiesStateScales", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec508L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.ODD", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec507L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055816");
    b.version(2);
    b.aggregate("environment", 0x354cc3720a9ec509L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec597L).optional(true).ordered(true).multiple(false).origin("3840659476812055817").done();
    b.aggregate("entity", 0x354cc3720a9ec50bL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec50eL).optional(true).ordered(true).multiple(true).origin("3840659476812055819").done();
    b.aggregate("entityName", 0x5be13da8667bda10L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x5be13da8667bda0cL).optional(true).ordered(true).multiple(true).origin("6620640720694532624").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Entity", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec50eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055822");
    b.version(2);
    b.property("showColors", 0x35a0391965764891L).type(PrimitiveTypeId.STRING).origin("3864151261523101841").done();
    b.property("showAttributes", 0x35a0391965764893L).type(PrimitiveTypeId.STRING).origin("3864151261523101843").done();
    b.aggregate("attributes", 0x354cc3720a9ec511L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(true).ordered(true).multiple(true).origin("3840659476812055825").done();
    b.aggregate("Min", 0x699ecf088dfe86d9L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec557L).optional(true).ordered(true).multiple(true).origin("7610748055951673049").done();
    b.aggregate("Max", 0x699ecf088dfe86e8L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec554L).optional(true).ordered(true).multiple(true).origin("7610748055951673064").done();
    b.aggregate("Sum", 0x699ecf088dfe86f9L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec560L).optional(true).ordered(true).multiple(true).origin("7610748055951673081").done();
    b.aggregate("Average", 0x699ecf088dfe870cL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec55aL).optional(true).ordered(true).multiple(true).origin("7610748055951673100").done();
    b.aggregate("Count", 0x4b1fb43d68b7eed7L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec55dL).optional(true).ordered(true).multiple(false).origin("5413243452965514967").done();
    b.aggregate("DefaultColor", 0x699ecf088dfc5bcbL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec585L).optional(true).ordered(true).multiple(false).origin("7610748055951530955").done();
    b.aggregate("MoreColors", 0x699ecf088dfc5bdfL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58aL).optional(true).ordered(true).multiple(false).origin("7610748055951530975").done();
    b.aggregate("ColorShade", 0x699ecf088dfc5bf6L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec592L).optional(true).ordered(true).multiple(false).origin("7610748055951530998").done();
    b.aggregate("shape", 0x354cc3720a9ec51aL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec575L).optional(true).ordered(true).multiple(false).origin("3840659476812055834").done();
    b.aggregate("MoreShapes", 0x699ecf088dfc954bL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec57bL).optional(true).ordered(true).multiple(true).origin("7610748055951545675").done();
    b.aggregate("colorOptions", 0x35a03919658b5ff9L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a039196585f0bdL).optional(true).ordered(true).multiple(false).origin("3864151261524484089").done();
    b.aggregate("shapeOptions", 0x35a0391965971d6cL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965961db8L).optional(true).ordered(true).multiple(false).origin("3864151261525253484").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "EntityReference", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d4552674aL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/2325324488110139210");
    b.version(2);
    b.associate("entity", 0x2045364d45859584L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec50eL).optional(true).origin("2325324488113493380").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnvironment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Environment", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec597L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055959");
    b.version(2);
    b.property("WorldSize", 0x6086ffb5de6c37a2L).type(PrimitiveTypeId.STRING).origin("6955527831106107298").done();
    b.property("PixelSize", 0x6086ffb5de6c37a4L).type(PrimitiveTypeId.STRING).origin("6955527831106107300").done();
    b.property("WrapHorizontal", 0x6086ffb5de6c37a7L).type(PrimitiveTypeId.STRING).origin("6955527831106107303").done();
    b.property("WrapVertical", 0x6086ffb5de6c37abL).type(PrimitiveTypeId.STRING).origin("6955527831106107307").done();
    b.property("BackGround", 0x6086ffb5de6c37b0L).type(PrimitiveTypeId.STRING).origin("6955527831106107312").done();
    b.aggregate("EnvEntity", 0x563ab269f9c57a4cL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5a4L).optional(true).ordered(true).multiple(true).origin("6213474804142799436").done();
    b.aggregate("attributes", 0x4b1fb43d68c187d7L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(true).ordered(true).multiple(true).origin("5413243452966143959").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnvironmentEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "EnvironmentEntity", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5a4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055972");
    b.version(2);
    b.property("Distribution", 0x6086ffb5de71b932L).type(PrimitiveTypeId.STRING).origin("6955527831106468146").done();
    b.property("showColor", 0x6086ffb5de71b934L).type(PrimitiveTypeId.STRING).origin("6955527831106468148").done();
    b.property("showAttributes", 0x36f982e7b7a0f5baL).type(PrimitiveTypeId.STRING).origin("3961341278978897338").done();
    b.property("showLocation", 0x36f982e7b7a2cd7cL).type(PrimitiveTypeId.STRING).origin("3961341278979018108").done();
    b.property("ChangeNeighbors", 0x6086ffb5de71b937L).type(PrimitiveTypeId.STRING).origin("6955527831106468151").done();
    b.property("ChangeSelf", 0x6086ffb5de71b93bL).type(PrimitiveTypeId.STRING).origin("6955527831106468155").done();
    b.aggregate("Coordinates", 0x563ab269f9c57957L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d0L).optional(true).ordered(true).multiple(true).origin("6213474804142799191").done();
    b.aggregate("Area", 0x563ab269f9c5795aL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c8L).optional(true).ordered(true).multiple(true).origin("6213474804142799194").done();
    b.aggregate("Density", 0x563ab269f9c5795eL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d6L).optional(true).ordered(true).multiple(false).origin("6213474804142799198").done();
    b.aggregate("ConditionalColor", 0x563ab269f9c57970L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58dL).optional(true).ordered(true).multiple(false).origin("6213474804142799216").done();
    b.aggregate("ColorShade", 0x4b1fb43d68cd0510L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec592L).optional(true).ordered(true).multiple(false).origin("5413243452966896912").done();
    b.aggregate("EnvironmentAttribute", 0x563ab269f9c57978L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5b7L).optional(true).ordered(true).multiple(false).origin("6213474804142799224").done();
    b.aggregate("DefaultColor", 0x36f982e7b7a0a354L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec585L).optional(true).ordered(true).multiple(false).origin("3961341278978876244").done();
    b.aggregate("MoreColors", 0x36f982e7b7a0a355L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58aL).optional(true).ordered(true).multiple(false).origin("3961341278978876245").done();
    b.aggregate("shape", 0x36f982e7b7a0a357L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec575L).optional(true).ordered(true).multiple(false).origin("3961341278978876247").done();
    b.aggregate("MoreShapes", 0x36f982e7b7a0a358L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec57bL).optional(true).ordered(true).multiple(true).origin("3961341278978876248").done();
    b.aggregate("colorOptions", 0x36f982e7b7a0a359L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a039196585f0bdL).optional(true).ordered(true).multiple(false).origin("3961341278978876249").done();
    b.aggregate("shapeOptions", 0x36f982e7b7a0a35aL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965961db8L).optional(true).ordered(true).multiple(false).origin("3961341278978876250").done();
    b.aggregate("Location", 0x36f982e7b7b1ba4eL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c7L).optional(true).ordered(true).multiple(false).origin("3961341278979996238").done();
    b.aggregate("Slider", 0x36f982e7b7b82d52L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x36f982e7b7b77956L).optional(true).ordered(true).multiple(false).origin("3961341278980418898").done();
    b.aggregate("SliderOption", 0x36f982e7b7b82d61L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x36f982e7b7b77a1eL).optional(true).ordered(true).multiple(false).origin("3961341278980418913").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExponential() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Exponential", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec550L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.StatisticalDistribution", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055888");
    b.version(2);
    b.property("mean", 0x354cc3720a9ec551L).type(PrimitiveTypeId.STRING).origin("3840659476812055889").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Expression", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c3L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056003");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFloat() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Float", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec536L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Type", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055862");
    b.version(2);
    b.property("min", 0x354cc3720a9ec537L).type(PrimitiveTypeId.STRING).origin("3840659476812055863").done();
    b.property("max", 0x354cc3720a9ec539L).type(PrimitiveTypeId.STRING).origin("3840659476812055865").done();
    b.aggregate("distribution", 0x354cc3720a9ec53cL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL).optional(true).ordered(true).multiple(false).origin("3840659476812055868").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGamma() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Gamma", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec541L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.StatisticalDistribution", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055873");
    b.version(2);
    b.property("alpha", 0x354cc3720a9ec542L).type(PrimitiveTypeId.STRING).origin("3840659476812055874").done();
    b.property("lambda", 0x354cc3720a9ec544L).type(PrimitiveTypeId.STRING).origin("3840659476812055876").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGraphicsWindow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "GraphicsWindow", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3864151261526742322");
    b.version(2);
    b.property("test", 0x35a0391965d266c1L).type(PrimitiveTypeId.STRING).origin("3864151261529138881").done();
    b.property("BackGround", 0x35a03919662de04bL).type(PrimitiveTypeId.STRING).origin("3864151261535133771").done();
    b.property("WrapHorizontal", 0x35a03919662de052L).type(PrimitiveTypeId.STRING).origin("3864151261535133778").done();
    b.property("PixelSize", 0x35a03919662de04eL).type(PrimitiveTypeId.STRING).origin("3864151261535133774").done();
    b.property("WrapVertical", 0x35a03919662ded2cL).type(PrimitiveTypeId.STRING).origin("3864151261535137068").done();
    b.property("WorldSize", 0x35a03919662f32cfL).type(PrimitiveTypeId.STRING).origin("3864151261535220431").done();
    b.aggregate("entityReference", 0x2045364d4552674eL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d4552674aL).optional(true).ordered(true).multiple(true).origin("2325324488110139214").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Integer", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec52eL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Type", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055854");
    b.version(2);
    b.property("min", 0x354cc3720a9ec52fL).type(PrimitiveTypeId.INTEGER).origin("3840659476812055855").done();
    b.property("max", 0x354cc3720a9ec531L).type(PrimitiveTypeId.INTEGER).origin("3840659476812055857").done();
    b.aggregate("distribution", 0x354cc3720a9ec534L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL).optional(true).ordered(true).multiple(false).origin("3840659476812055860").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntentionEffect() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "IntentionEffect", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d4534e56bL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/2325324488108205419");
    b.version(2);
    b.property("Who", 0x2045364d4534e56cL).type(PrimitiveTypeId.STRING).origin("2325324488108205420").done();
    b.property("What", 0x2045364d4534e56fL).type(PrimitiveTypeId.STRING).origin("2325324488108205423").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntentions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Intentions", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d452f6abbL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/2325324488107846331");
    b.version(2);
    b.property("Entitys", 0x2045364d4534e4ffL).type(PrimitiveTypeId.STRING).origin("2325324488108205311").done();
    b.property("Enviroment", 0x2045364d4534e513L).type(PrimitiveTypeId.STRING).origin("2325324488108205331").done();
    b.property("Attribut", 0x2045364d4534e52aL).type(PrimitiveTypeId.STRING).origin("2325324488108205354").done();
    b.property("Effect", 0x770189b79f05a3abL).type(PrimitiveTypeId.STRING).origin("8575286587230102443").done();
    b.property("EntitysEffected", 0x2045364d4534e537L).type(PrimitiveTypeId.STRING).origin("2325324488108205367").done();
    b.property("EnviromentEffected", 0x2045364d4534e546L).type(PrimitiveTypeId.STRING).origin("2325324488108205382").done();
    b.property("AttributEffected", 0x2045364d4534e557L).type(PrimitiveTypeId.STRING).origin("2325324488108205399").done();
    b.associate("entity", 0x2045364d453f5598L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec50eL).optional(true).origin("2325324488108889496").done();
    b.associate("environment", 0x2045364d453f559fL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec597L).optional(true).origin("2325324488108889503").done();
    b.aggregate("effectedAtributes", 0x2045364d4534e584L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x2045364d4534e56bL).optional(true).ordered(true).multiple(false).origin("2325324488108205444").done();
    b.aggregate("conditional", 0x2045364d452f6f64L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c0L).optional(true).ordered(true).multiple(true).origin("2325324488107847524").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Location", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c7L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.SpecificLocation", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c6L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056007");
    b.version(2);
    b.property("showLocation", 0x36f982e7b7aee383L).type(PrimitiveTypeId.STRING).origin("3961341278979810179").done();
    b.aggregate("Area", 0x563ab269f9c35f70L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c8L).optional(true).ordered(true).multiple(false).origin("6213474804142661488").done();
    b.aggregate("SpexificXY", 0x563ab269f9c35f73L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5cbL).optional(true).ordered(true).multiple(false).origin("6213474804142661491").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMax() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Max", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec554L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055892");
    b.version(2);
    b.associate("attribute", 0x354cc3720a9ec555L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(false).origin("3840659476812055893").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMin() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Min", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec557L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055895");
    b.version(2);
    b.associate("min", 0x354cc3720a9ec558L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(false).origin("3840659476812055896").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoreColors() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "MoreColors", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58aL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Color", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec574L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055946");
    b.version(2);
    b.aggregate("ConditionalColor", 0x354cc3720a9ec58bL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec58dL).optional(true).ordered(true).multiple(true).origin("3840659476812055947").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoreShapes() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "MoreShapes", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec57bL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Shape", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec573L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055931");
    b.version(2);
    b.aggregate("ShapeInstance", 0x354cc3720a9ec57cL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec57eL).optional(false).ordered(true).multiple(true).origin("3840659476812055932").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNames() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Names", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x5be13da8667bda0cL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/6620640720694532620");
    b.version(2);
    b.property("name", 0x5be13da8667bda0dL).type(PrimitiveTypeId.STRING).origin("6620640720694532621").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNormal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Normal", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec547L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.StatisticalDistribution", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055879");
    b.version(2);
    b.property("mean", 0x354cc3720a9ec548L).type(PrimitiveTypeId.STRING).origin("3840659476812055880").done();
    b.property("standard_deviation", 0x354cc3720a9ec54aL).type(PrimitiveTypeId.STRING).origin("3840659476812055882").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForODD() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ODD", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec507L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055815");
    b.version(2);
    b.aggregate("text", 0x5be13da86678bf86L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x5be13da866785777L).optional(true).ordered(true).multiple(true).origin("6620640720694329222").done();
    b.aggregate("EntitiesStateScale", 0x699ecf088dfadfbcL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec508L).optional(true).ordered(true).multiple(false).origin("7610748055951433660").done();
    b.aggregate("action", 0x2045364d4536a910L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a039196620dc12L).optional(true).ordered(true).multiple(false).origin("2325324488108321040").done();
    b.aggregate("test", 0x35a0391965e0c797L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965de199dL).optional(true).ordered(true).multiple(false).origin("3864151261530081175").done();
    b.aggregate("graphicsWindow", 0x2045364d45665038L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965add532L).optional(true).ordered(true).multiple(false).origin("2325324488111444024").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPoisson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Poisson", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec54dL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.StatisticalDistribution", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055885");
    b.version(2);
    b.property("mean", 0x4b1fb43d68a891f2L).type(PrimitiveTypeId.STRING).origin("5413243452964508146").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Shape", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec573L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055923");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapeInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ShapeInstance", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec57eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055934");
    b.version(2);
    b.property("ShapeID", 0x354cc3720a9ec581L).type(MetaIdFactory.dataTypeId(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec579L)).origin("3840659476812055937").done();
    b.aggregate("Conditional", 0x354cc3720a9ec583L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c0L).optional(true).ordered(true).multiple(true).origin("3840659476812055939").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapeOptions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "ShapeOptions", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965961db8L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3864151261525188024");
    b.version(2);
    b.property("ShapeOption", 0x35a0391965961db9L).type(PrimitiveTypeId.STRING).origin("3864151261525188025").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSlider() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Slider", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x36f982e7b7b77956L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3961341278980372822");
    b.version(2);
    b.property("name", 0x36f982e7b7b77957L).type(PrimitiveTypeId.STRING).origin("3961341278980372823").done();
    b.property("showSlider", 0x36f982e7b7b82d82L).type(PrimitiveTypeId.STRING).origin("3961341278980418946").done();
    b.property("minAmount", 0x36f982e7b7b77959L).type(PrimitiveTypeId.STRING).origin("3961341278980372825").done();
    b.property("maxAmount", 0x36f982e7b7b7795cL).type(PrimitiveTypeId.STRING).origin("3961341278980372828").done();
    b.property("slideAmount", 0x36f982e7b7b77960L).type(PrimitiveTypeId.STRING).origin("3961341278980372832").done();
    b.aggregate("SliderOption", 0x36f982e7b7b8afbcL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x36f982e7b7b77a1eL).optional(true).ordered(true).multiple(false).origin("3961341278980452284").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSliderOption() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "SliderOption", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x36f982e7b7b77a1eL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3961341278980373022");
    b.version(2);
    b.property("showSlider", 0x36f982e7b7b77a1fL).type(PrimitiveTypeId.STRING).origin("3961341278980373023").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpecificLocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "SpecificLocation", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c6L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056006");
    b.version(2);
    b.aggregate("Location", 0x563ab269f9c35f20L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c7L).optional(true).ordered(true).multiple(false).origin("6213474804142661408").done();
    b.aggregate("Density", 0x563ab269f9c35faeL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d6L).optional(true).ordered(true).multiple(false).origin("6213474804142661550").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpecificXY() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "SpecificXY", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5cbL);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Location", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5c7L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812056011");
    b.version(2);
    b.aggregate("Coordinates", 0x354cc3720a9ec5ceL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec5d0L).optional(false).ordered(true).multiple(true).origin("3840659476812056014").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatisticalDistribution() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "StatisticalDistribution", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec53eL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055870");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "String", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec523L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.Type", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055843");
    b.version(2);
    b.aggregate("Stringvalue", 0x354cc3720a9ec526L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec523L).optional(false).ordered(true).multiple(true).origin("3840659476812055846").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStringvalue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Stringvalue", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec528L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.String", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec523L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055848");
    b.version(2);
    b.property("value", 0x354cc3720a9ec52bL).type(PrimitiveTypeId.STRING).origin("3840659476812055851").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSum() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Sum", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec560L);
    b.class_(false, false, false);
    b.super_("formalodd.structure.AgentStatistic", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec553L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055904");
    b.version(2);
    b.associate("attribute", 0x354cc3720a9ec561L).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL).optional(false).origin("3840659476812055905").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "Type", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055842");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUserComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "UserComment", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x5be13da866785777L);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/6620640720694302583");
    b.version(2);
    b.property("text", 0x5be13da866785778L).type(PrimitiveTypeId.STRING).origin("6620640720694302584").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUserDefinedAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "UserDefinedAttribute", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec51fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3840659476812055839");
    b.version(2);
    b.property("Stability", 0x354cc3720a9ec5a2L).type(PrimitiveTypeId.BOOLEAN).origin("3840659476812055970").done();
    b.aggregate("type", 0x4b1fb43d68ac66feL).target(0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x354cc3720a9ec522L).optional(false).ordered(true).multiple(false).origin("5413243452964759294").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("formalodd", "test", 0x32c6af6fc92141d7L, 0xa19e61a23bec1a47L, 0x35a0391965de199dL);
    b.class_(false, false, false);
    b.origin("r:a0cde16a-59bc-4c03-980f-3141a0d99865(formalodd.structure)/3864151261529905565");
    b.version(2);
    return b.create();
  }
}
