  __INTERNAL__stop ; variable to indicate that there is a stop
  votes-changed ; 
]

patches-own [
  Voter ; 
  surrounding-blue-votes ; 
]

to setup
  clear-all
  set __INTERNAL__stop false
  ask patches [
    set Voter 0 ; no initialization defined
    set surrounding-blue-votes 0 ; no initialization defined
    set pcolor green
    if (random 100) < 50[
      set pcolor blue
    ]
  ]
  set votes-changed 0 ; no initialization defined
  reset-ticks
end

to count-blu [ _me ] ; 
ask _me [ ; all access is to _me
  set surrounding-blue-votes    max (list 0 min (list 8 (count neighbors with [ pcolor = blue ])))
]
end

to Vote-Blue [ _me ] ; 
ask _me [ ; all access is to _me
  set votes-changed    max (list 0 min (list 1 (0)))
  set Voter    max (list 0 min (list 1 (1)))
]
end

to Vote-Green [ _me ] ; 
ask _me [ ; all access is to _me
  set Voter    max (list 0 min (list 1 (0)))
]
end

to change-vote [ _me ] ; bytt farge til flertallet, ingen endring i tilfelle stemmene er delt
ask _me [ ; all access is to _me
  if surrounding-blue-votes < 4 [
    set pcolor green
    set votes-changed    max (list 0 min (list 1 (1)))
  ]
  if surrounding-blue-votes > 4 [
    set pcolor blue
    set votes-changed    max (list 0 min (list 1 (1)))
  ]
]
end

to go
  if __INTERNAL__stop [ ; stop button was pressed
    set __INTERNAL__stop false
    stop
  ]
  ask patches with [ pcolor = blue ] [
    Vote-Blue self
  ]
  ask patches with [ pcolor = green ] [
    Vote-Green self
  ]
  ask  patches  [
    count-blu self
  ]
  ask  patches  [
    change-vote self
  ]
  tick
end

to stopping
  set __INTERNAL__stop true
end

; Automatically generated by ODD2NetLogo.
; See Info tab for more information.
@#$#@#$#@
GRAPHICS-WINDOW
250
10
100
100
-1
-1
2
1
10
1
1
1
0
0
0
1
-100
100
-100
100
1
1
1
ticks
30.0

BUTTON
10
10
80
40
setup
setup
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

BUTTON
90
10
160
40
go
go
T
1
T
OBSERVER
NIL
NIL
NIL
NIL
0

BUTTON
170
10
240
40
stop
stopping
NIL
1
T
OBSERVER
NIL
NIL
NIL
NIL
1

@#$#@#$#@
## NetLogo info tab


## Model Role


## Target Audience

## Purpose

## Research Question

## Entities
### environment entities Voter and surrounding-blue-votes
 with attributes Voter, surrounding-blue-votes

## Model Parameters
votes-changed

## Attributes that Change During the Simulation
votes-changed
Voter
surrounding-blue-votes

## User Experimentation Options
The user can change the following attributes to create different experiments:

## Data Shown in the Simulation

@#$#@#$#@
@#$#@#$#@
NetLogo 6.1.1
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
@#$#@#$#@
