<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="odd2abm_2" nsURI="http://www.example.org/odd2abm_2" nsPrefix="odd2abm_2">
  <eClassifiers xsi:type="ecore:EClass" name="ODD" eSuperTypes="#//IDescribedConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processandscheduling" lowerBound="1"
        eType="#//ProcessOverviewAndScheduling" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_designconcepts" eType="#//DesignConcepts"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modeldescription" lowerBound="1"
        eType="#//ModelDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodels" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experiments" lowerBound="1"
        eType="#//Experiments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale4init" eType="#//Rationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationales" upperBound="-1"
        eType="#//RationaleReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessOverviewAndScheduling">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="InformalText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignConcepts"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedAttributes"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//ModelCategories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchQuestion" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetGroup" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purposeDescription" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalDescriptions" upperBound="-1"
        eType="#//DescriptionElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Experiments"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rationale">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base4Rationale" eType="#//RationaleKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RationaleReference"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelCategories"/>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptionText" upperBound="-1"
        eType="#//InformalText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDescribedConcept" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RationaleKind"/>
</ecore:EPackage>
