<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expressionAccessPart" nsURI="http://www.example.org/expressionAccessPart"
    nsPrefix="expressionAccessPart">
  <eClassifiers xsi:type="ecore:EClass" name="Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Actual">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseGeneralEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseattribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetattribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" upperBound="-1"
        eType="#//Actual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Function" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="todo_FilterIndex" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterCondition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityAccess" eSuperTypes="#//SelectExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//GeneralEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actual" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementWise" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralEntity"/>
</ecore:EPackage>
