<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="refConcepts" nsURI="http://www.example.org/refConcepts" nsPrefix="refConcepts">
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyEntity" eSuperTypes="#//EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyEnvironment" eSuperTypes="#//EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmententity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmententity" eType="#//EnvironmentEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteEntityReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalentity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genentity" eType="#//GenEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkReference" eSuperTypes="#//EntityReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" eType="#//Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//GenEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//GenEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEntity" eSuperTypes="#//GenEntity"/>
</ecore:EPackage>
