<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="odd2abm_2" nsURI="http://www.example.org/odd2abm_2" nsPrefix="odd2abm_2">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessOverviewAndScheduling">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Procedures" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rationale4Schedule" eType="#//Rationale"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endconditions" upperBound="-1"
        eType="#//EndCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codes" upperBound="-1"
        eType="#//code" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codereference" upperBound="-1"
        eType="#//CodeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schedule" upperBound="-1"
        eType="#//ActionCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" upperBound="-1"
        eType="#//EntityReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partner2" lowerBound="1"
        eType="#//EntityReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColorEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rationale"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locals" upperBound="-1"
        eType="#//LetActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EEnum" name=".SpecialEntities"/>
  <eClassifiers xsi:type="ecore:EClass" name="foreach">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" eType="#//.SpecialEntities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="1"
        upperBound="-1" eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//INamedConceptODD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityreference" lowerBound="1"
        eType="#//EntityReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="code" eSuperTypes="#//IDescribedConcept #//IRationaledConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionCall" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" upperBound="-1"
        eType="#//Actual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="called" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="code" lowerBound="1" eType="#//code"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INamedConceptODD"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actual"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRationaledConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDescribedConcept"/>
</ecore:EPackage>
