<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Expression" nsURI="http://www.example.org/initialization" nsPrefix="initialization">
  <eClassifiers xsi:type="ecore:EClass" name="AttributeInit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisation" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//UserDefinedAttribute.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisation" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="#//InitialEntityDistribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="_Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationNumberOfEntities"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationDistribution"
        eType="#//InitialEntityDistribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initAttributes" upperBound="-1"
        eType="#//AttributeInit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntitiesStatesScales">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesInit" upperBound="-1"
        eType="#//EntityReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesInit" upperBound="-1"
        eType="#//AttributeInit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="#//AreaEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="themiswhatdoesthegridrepresent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisationLocation"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Density" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="percentage" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialEntityDistribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="Everywhere" eSuperTypes="#//Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AreaEnumeration"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomNumber" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Slider" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slideAmount" eType="#//number"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startValue" eType="#//number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomUniform" eSuperTypes="#//RandomNumber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomNormal" eSuperTypes="#//RandomNumber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stdev" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="number" instanceTypeName="newDataType2"/>
</ecore:EPackage>
